_target_: src.data.yahoo_datamodule.YahooDatamodule
num_classes: 10 #10
num_workers: 0
normalize: True
seed: 52 #42 #32
batch_size: 16
shuffle: True
num_clients: 100
val_split: 0.2
pub_size: 0.0001
transform: False
m: 10
available_clients: 100
local_steps: 5

