_target_: fl_client.client_celoss.Client

client_id: ???
#device: ???
local_steps: ${datamodule.local_steps}
task: ${task}
learning_rate: ${optim.lr}
batch_size: ${datamodule.batch_size}
topk: False #True #topk: True #should be false with cifar10
